name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build Project with Gradle
      run: ./gradlew assemble

    - name: Run Tests with Gradle
      run: ./gradlew test
